### ISSUE TITLE
Provisioning slave fails, jenkins_data crashes

### ISSUE THREAD

**Issue by plorent** [maxfields2000/dockerjenkins_tutorial#19]
On OSX 10.11.5, running 1.12.0-rc4, build e4a0dbc, experimental, creating of the jenkins_slave fails with:

`Error in provisioning; template='DockerTemplate{configVersion=2, labelString='testslave', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@52deb96, remoteFsMapping='/home/jenkins', remoteFs='/home/jenkins', instanceCap=1, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@4e4e5b9e, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=jenkins_slave}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='Local Docker'
com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}`

Additionally, jenkins_data crashes.

Don't have a clue yet why. Maybe you have an idea on how to resolve?

**Comment by maxfields2000** [comment]
Absolutely! Just started getting reports of this. The issue is: 1.12.0-rc4 (your docker version).  The docker-plugin is incompatible with Docker 1.12.0.  

Which means it's probably timet o move to "Yet Another Docker Plugin" (where the work continued). Which means it's time for me to update all this with how to do that.

In the short term, if you use Docker 1.10 or 1.11 you shouldn't have issues. (I'd advocate for not using an RC version of Docker anyway).

**Comment by maxfields2000** [comment]
#20 Duplicates this issue.

**Comment by plorent** [comment]
Makes sense. I'll downgrade, thanks!
